services:
  ingress:
    image: kvin/dstack-ingress@sha256:fee7a6075a271adb5a5ff72ff3ff49bcb9e22d5f4c9fa68fa683cfb3932f911c
    ports:
      - "443:443"
    environment:
      - DNS_PROVIDER=cloudflare
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAIN=tee.sp1-lumiere.xyz
      - CLIENT_MAX_BODY_SIZE=2g
      - GATEWAY_DOMAIN=_.${DSTACK_GATEWAY_DOMAIN}
      - CERTBOT_EMAIL=aurelien@succinct.xyz
      - SET_CAA=true
      - TARGET_ENDPOINT=grpc://server:8080
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /var/run/tappd.sock:/var/run/tappd.sock
      - cert-data:/etc/letsencrypt
    restart: unless-stopped
  server:
    image: public.ecr.aws/succinct-labs/sp1-tee-private-proving:server@sha256:77df8aa44f1fae305e5d25c6c4fd252a2c4406480077df41f870719b0166f2f2
    environment:
      - HOSTNAME=https://tee.sp1-lumiere.xyz
      - NETWORK_RPC_URL=https://rpc.production.succinct.xyz
      - FULFILLER_PRIVATE_KEY=${FULFILLER_PRIVATE_KEY}
      - RUST_LOG=info
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
  fulfiller:
    image: public.ecr.aws/succinct-labs/sp1-tee-private-proving:fulfiller@sha256:c2c97b2de47d5b48a35b6fa685cdad9196c6a6e267ce34f09e7c7b4925d48a1f
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NETWORK_RPC_URL=https://rpc.production.succinct.xyz
      - PRIVATE_SERVER_RPC_URL=http://server:8080
      - FULFILLER_PRIVATE_KEY=${FULFILLER_PRIVATE_KEY}
      - PROGRAMS_S3_REGION=us-east-2
      - RUST_LOG=info
    depends_on:
      - moongate
    restart: unless-stopped
  moongate:
    image: public.ecr.aws/succinct-labs/sp1-gpu:86a2bbf
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  cert-data: # Persistent volume for certificates
